# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='slug',
            field=models.SlugField(default='n/a'),
            preserve_default=False,
        ),
    ]
