# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solos', '0002_auto_20171010_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='solo',
            name='album',
            field=models.CharField(default='n/a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solo',
            name='end_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solo',
            name='start_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
