# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='title',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
